# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

---
################################
## Jaeger (all-in-one) Deployment
################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-jaeger
  labels:
    tier: airflow
    component: jaeger
    release: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: airflow
      component: jaeger
      release: airflow
  template:
    metadata:
      labels:
        tier: airflow
        component: jaeger
        release: airflow
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.57
          imagePullPolicy: IfNotPresent
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          ports:
            - name: ui
              containerPort: 16686
              protocol: TCP
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 15
            periodSeconds: 15
---
################################
## Jaeger Service
################################
apiVersion: v1
kind: Service
metadata:
  name: airflow-jaeger
  labels:
    tier: airflow
    component: jaeger
    release: airflow
spec:
  type: ClusterIP
  selector:
    tier: airflow
    component: jaeger
    release: airflow
  ports:
    - name: ui
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
