#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""Add end_date index on task_instance.

Revision ID: 53dc33920ac3
Revises: 0fd0c178cbe8
Create Date: 2024-05-29 14:53:30.940486

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "53dc33920ac3"
down_revision = "0fd0c178cbe8"
branch_labels = None
depends_on = None
airflow_version = "2.9.2"


def upgrade():
    """Apply add end_date index on task_instance."""
    with op.batch_alter_table("task_instance", schema=None) as batch_op:
        batch_op.create_index(
            "ti_end_date",
            ["end_date"],
            unique=False,
            postgresql_where=sa.text("end_date IS NOT NULL"),
            sqlite_where=sa.text("end_date IS NOT NULL"),
        )


def downgrade():
    """Unapply add end_date index on task_instance."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_instance", schema=None) as batch_op:
        batch_op.drop_index(
            "ti_end_date",
            postgresql_where=sa.text("end_date IS NOT NULL"),
            sqlite_where=sa.text("end_date IS NOT NULL"),
        )
