// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package genlicense_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/apache/airflow/go-sdk/internal/genlicense"
)

func writeFile(t *testing.T, body string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), "out.gen.go")
	require.NoError(t, os.WriteFile(path, []byte(body), 0o644))
	return path
}

func readFile(t *testing.T, path string) string {
	t.Helper()

	body, err := os.ReadFile(path)
	require.NoError(t, err)
	return string(body)
}

func TestEnsureHeaderInsertsAfterTheCodeGeneratedLine(t *testing.T) {
	path := writeFile(t, "// Code generated by a tool, DO NOT EDIT.\n\npackage out\n")

	require.NoError(t, genlicense.EnsureHeader(path))

	lines := strings.Split(readFile(t, path), "\n")
	assert.Equal(t, "// Code generated by a tool, DO NOT EDIT.", lines[0],
		"golines leaves the file alone only while this line is first")
	assert.Equal(t, "// Licensed to the Apache Software Foundation (ASF) under one", lines[1])
	assert.Contains(t, readFile(t, path), "\npackage out\n")
}

func TestEnsureHeaderIsIdempotent(t *testing.T) {
	path := writeFile(t, "// Code generated by a tool, DO NOT EDIT.\n\npackage out\n")

	require.NoError(t, genlicense.EnsureHeader(path))
	once := readFile(t, path)
	require.NoError(t, genlicense.EnsureHeader(path))

	assert.Equal(t, once, readFile(t, path), "a generator calls it on every run")
}

func TestEnsureHeaderPrependsWhenThereIsNoCodeGeneratedLine(t *testing.T) {
	path := writeFile(t, "package out\n")

	require.NoError(t, genlicense.EnsureHeader(path))

	assert.True(
		t,
		strings.HasPrefix(readFile(t, path), "// Licensed to the Apache Software Foundation"),
	)
}

func TestEnsureHeaderReportsAMissingFile(t *testing.T) {
	assert.Error(t, genlicense.EnsureHeader(filepath.Join(t.TempDir(), "absent.go")))
}
