/*
 * Airflow API (Stable)
 * Apache Airflow management API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@airflow.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.apache.airflow.client.api;

import org.apache.airflow.client.ApiException;
import org.openapitools.client.model.Config;
import org.openapitools.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConfigApi
 */
public class ConfigApiTest {

    private final ConfigApi api = new ConfigApi();

    /**
     * Get current configuration
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void airflowApiConnexionEndpointsConfigEndpointGetConfigTest() throws ApiException {
        //
        //Integer limit = null;
        //
        //Integer offset = null;
        //
        //Config response = api.airflowApiConnexionEndpointsConfigEndpointGetConfig(limit, offset);

        // TODO: test validations
    }
}
