#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
set -euo pipefail

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

BREEZE_BINARY=Breeze2

function check_breeze_installed() {
    if ! command -v ${BREEZE_BINARY} &> /dev/null; then
        echo
        echo "You need to install pipx and run:"
        echo
        echo "    pipx install -e '${MY_DIR}/dev/breeze/'"
        echo
        echo
        if "${MY_DIR}/scripts/tools/confirm" "Installing pipx and Breeze?"; then
            python -m pip install pipx --upgrade
            pipx install -e "${MY_DIR}/dev/breeze/"
            ${BREEZE_BINARY} setup-autocomplete
        else
            exit
        fi
    fi
}

${BREEZE_BINARY} "${@}"
