# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
from __future__ import annotations

from typing import Literal

from airflow.providers.standard.api_fastapi.execution_api.datamodels.hitl import (
    GetHITLResponseContentDetailPayload,
    HITLInputRequestResponse,
    HITLResponseContentDetail,
    UpdateHITLResponsePayload,
)


class CreateHITLResponsePayload(HITLInputRequestResponse):
    """Add the input request part of a Human-in-the-loop response."""

    type: Literal["CreateHITLResponsePayload"] = "CreateHITLResponsePayload"


class HITLInputRequestResponseResult(HITLInputRequestResponse):
    """Response to CreateHITLResponsePayload request."""

    type: Literal["HITLInputRequestResponseResult"] = "HITLInputRequestResponseResult"


class GetHITLResponseContentDetail(GetHITLResponseContentDetailPayload):
    """Get the response content part of a Human-in-the-loop response."""

    type: Literal["GetHITLResponseContentDetail"] = "GetHITLResponseContentDetail"


class UpdateHITLResponse(UpdateHITLResponsePayload):
    """Update the response content part of an existing Human-in-the-loop response."""

    type: Literal["UpdateHITLResponse"] = "UpdateHITLResponse"


class HITLResponseContentDetailResult(HITLResponseContentDetail):
    """Response to GetHITLResponseContentDetail request."""

    type: Literal["HITLResponseContentDetailResult"] = "HITLResponseContentDetailResult"

    @classmethod
    def from_api_response(cls, response: HITLResponseContentDetail) -> HITLResponseContentDetailResult:
        """
        Create result class from API Response.

        API Response is autogenerated from the API schema, so we need to convert it to Result
        for communication between the Supervisor and the task process since it needs a
        discriminator field.
        """
        return cls(**response.model_dump(exclude_defaults=True), type="HITLResponseContentDetailResult")
