#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM mysql:5.7

COPY scripts/ci/data/baby_names.csv /var/lib/mysql-files/baby_names.csv
COPY scripts/docker/unittest/grant_airflow.sh /docker-entrypoint-initdb.d/
COPY scripts/docker/unittest/load_data.sh /docker-entrypoint-initdb.d/
