/*
 * Airflow API (Stable)
 *
 * Apache Airflow management API.
 *
 * API version: 1.0.0
 * Contact: dev@airflow.apache.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package airflow
// TaskExtraLinks struct for TaskExtraLinks
type TaskExtraLinks struct {
	ClassRef ClassReference `json:"class_ref,omitempty"`
}
