/*
 * Airflow API (Stable)
 *
 * Apache Airflow management API.
 *
 * API version: 1.0.0
 * Contact: dev@airflow.apache.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package airflow
// TaskState the model 'TaskState'
type TaskState string

// List of TaskState
const (
	TASKSTATE_SUCCCESS TaskState = "succcess"
	TASKSTATE_RUNNING TaskState = "running"
	TASKSTATE_FAILED TaskState = "failed"
	TASKSTATE_UPSTREAM_FAILED TaskState = "upstream_failed"
	TASKSTATE_SKIPPED TaskState = "skipped"
	TASKSTATE_UP_FOR_RETRY TaskState = "up_for_retry"
	TASKSTATE_UP_FOR_RESCHEDULE TaskState = "up_for_reschedule"
	TASKSTATE_QUEUED TaskState = "queued"
	TASKSTATE_NONE TaskState = "none"
	TASKSTATE_SCHEDULED TaskState = "scheduled"
)
