# coding: utf-8

"""
    Airflow API (Stable)

    Apache Airflow management API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: dev@airflow.apache.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import airflow_client
from airflow_client.api.event_log_api import EventLogApi  # noqa: E501
from airflow_client.rest import ApiException


class TestEventLogApi(unittest.TestCase):
    """EventLogApi unit test stubs"""

    def setUp(self):
        self.api = airflow_client.api.event_log_api.EventLogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_airflow_api_connexion_endpoints_event_log_endpoint_get_event_log(self):
        """Test case for airflow_api_connexion_endpoints_event_log_endpoint_get_event_log

        Get a log entry  # noqa: E501
        """
        pass

    def test_airflow_api_connexion_endpoints_event_log_endpoint_get_event_logs(self):
        """Test case for airflow_api_connexion_endpoints_event_log_endpoint_get_event_logs

        Get all log entries from event log  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
