/**
 * Airflow API (Stable)
 * Apache Airflow management API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@airflow.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AirflowApiStable);
  }
}(this, function(expect, AirflowApiStable) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AirflowApiStable.DAGDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DAGDetail', function() {
    it('should create an instance of DAGDetail', function() {
      // uncomment below and update the code to test DAGDetail
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be.a(AirflowApiStable.DAGDetail);
    });

    it('should have the property dagId (base name: "dag_id")', function() {
      // uncomment below and update the code to test the property dagId
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property rootDagId (base name: "root_dag_id")', function() {
      // uncomment below and update the code to test the property rootDagId
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property isPaused (base name: "is_paused")', function() {
      // uncomment below and update the code to test the property isPaused
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property isSubdag (base name: "is_subdag")', function() {
      // uncomment below and update the code to test the property isSubdag
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property fileloc (base name: "fileloc")', function() {
      // uncomment below and update the code to test the property fileloc
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property fileToken (base name: "file_token")', function() {
      // uncomment below and update the code to test the property fileToken
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property owners (base name: "owners")', function() {
      // uncomment below and update the code to test the property owners
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property scheduleInterval (base name: "schedule_interval")', function() {
      // uncomment below and update the code to test the property scheduleInterval
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property timezone (base name: "timezone")', function() {
      // uncomment below and update the code to test the property timezone
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property catchup (base name: "catchup")', function() {
      // uncomment below and update the code to test the property catchup
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property orientation (base name: "orientation")', function() {
      // uncomment below and update the code to test the property orientation
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property concurrency (base name: "concurrency")', function() {
      // uncomment below and update the code to test the property concurrency
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "start_date")', function() {
      // uncomment below and update the code to test the property startDate
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property dagRunTimeout (base name: "dag_run_timeout")', function() {
      // uncomment below and update the code to test the property dagRunTimeout
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property docMd (base name: "doc_md")', function() {
      // uncomment below and update the code to test the property docMd
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

    it('should have the property defaultView (base name: "default_view")', function() {
      // uncomment below and update the code to test the property defaultView
      //var instane = new AirflowApiStable.DAGDetail();
      //expect(instance).to.be();
    });

  });

}));
