/**
 * Airflow API (Stable)
 * Apache Airflow management API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@airflow.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AirflowApiStable);
  }
}(this, function(expect, AirflowApiStable) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AirflowApiStable.EventLog();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EventLog', function() {
    it('should create an instance of EventLog', function() {
      // uncomment below and update the code to test EventLog
      //var instane = new AirflowApiStable.EventLog();
      //expect(instance).to.be.a(AirflowApiStable.EventLog);
    });

    it('should have the property eventLogId (base name: "event_log_id")', function() {
      // uncomment below and update the code to test the property eventLogId
      //var instane = new AirflowApiStable.EventLog();
      //expect(instance).to.be();
    });

    it('should have the property when (base name: "when")', function() {
      // uncomment below and update the code to test the property when
      //var instane = new AirflowApiStable.EventLog();
      //expect(instance).to.be();
    });

    it('should have the property dagId (base name: "dag_id")', function() {
      // uncomment below and update the code to test the property dagId
      //var instane = new AirflowApiStable.EventLog();
      //expect(instance).to.be();
    });

    it('should have the property taskId (base name: "task_id")', function() {
      // uncomment below and update the code to test the property taskId
      //var instane = new AirflowApiStable.EventLog();
      //expect(instance).to.be();
    });

    it('should have the property event (base name: "event")', function() {
      // uncomment below and update the code to test the property event
      //var instane = new AirflowApiStable.EventLog();
      //expect(instance).to.be();
    });

    it('should have the property executionDate (base name: "execution_date")', function() {
      // uncomment below and update the code to test the property executionDate
      //var instane = new AirflowApiStable.EventLog();
      //expect(instance).to.be();
    });

    it('should have the property owner (base name: "owner")', function() {
      // uncomment below and update the code to test the property owner
      //var instane = new AirflowApiStable.EventLog();
      //expect(instance).to.be();
    });

    it('should have the property extra (base name: "extra")', function() {
      // uncomment below and update the code to test the property extra
      //var instane = new AirflowApiStable.EventLog();
      //expect(instance).to.be();
    });

  });

}));
