/**
 * Airflow API (Stable)
 * Apache Airflow management API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@airflow.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RelativeDelta model module.
 * @module model/RelativeDelta
 * @version 1.0.0
 */
class RelativeDelta {
    /**
     * Constructs a new <code>RelativeDelta</code>.
     * @alias module:model/RelativeDelta
     * @param type {String} 
     */
    constructor(type) { 
        
        RelativeDelta.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['__type'] = type;
    }

    /**
     * Constructs a <code>RelativeDelta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RelativeDelta} obj Optional instance to populate.
     * @return {module:model/RelativeDelta} The populated <code>RelativeDelta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RelativeDelta();

            if (data.hasOwnProperty('__type')) {
                obj['__type'] = ApiClient.convertToType(data['__type'], 'String');
            }
            if (data.hasOwnProperty('years')) {
                obj['years'] = ApiClient.convertToType(data['years'], 'Number');
            }
            if (data.hasOwnProperty('months')) {
                obj['months'] = ApiClient.convertToType(data['months'], 'Number');
            }
            if (data.hasOwnProperty('days')) {
                obj['days'] = ApiClient.convertToType(data['days'], 'Number');
            }
            if (data.hasOwnProperty('leapdays')) {
                obj['leapdays'] = ApiClient.convertToType(data['leapdays'], 'Number');
            }
            if (data.hasOwnProperty('hours')) {
                obj['hours'] = ApiClient.convertToType(data['hours'], 'Number');
            }
            if (data.hasOwnProperty('minutes')) {
                obj['minutes'] = ApiClient.convertToType(data['minutes'], 'Number');
            }
            if (data.hasOwnProperty('seconds')) {
                obj['seconds'] = ApiClient.convertToType(data['seconds'], 'Number');
            }
            if (data.hasOwnProperty('microseconds')) {
                obj['microseconds'] = ApiClient.convertToType(data['microseconds'], 'Number');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('month')) {
                obj['month'] = ApiClient.convertToType(data['month'], 'Number');
            }
            if (data.hasOwnProperty('day')) {
                obj['day'] = ApiClient.convertToType(data['day'], 'Number');
            }
            if (data.hasOwnProperty('hour')) {
                obj['hour'] = ApiClient.convertToType(data['hour'], 'Number');
            }
            if (data.hasOwnProperty('minute')) {
                obj['minute'] = ApiClient.convertToType(data['minute'], 'Number');
            }
            if (data.hasOwnProperty('second')) {
                obj['second'] = ApiClient.convertToType(data['second'], 'Number');
            }
            if (data.hasOwnProperty('microsecond')) {
                obj['microsecond'] = ApiClient.convertToType(data['microsecond'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} __type
 */
RelativeDelta.prototype['__type'] = undefined;

/**
 * @member {Number} years
 */
RelativeDelta.prototype['years'] = undefined;

/**
 * @member {Number} months
 */
RelativeDelta.prototype['months'] = undefined;

/**
 * @member {Number} days
 */
RelativeDelta.prototype['days'] = undefined;

/**
 * @member {Number} leapdays
 */
RelativeDelta.prototype['leapdays'] = undefined;

/**
 * @member {Number} hours
 */
RelativeDelta.prototype['hours'] = undefined;

/**
 * @member {Number} minutes
 */
RelativeDelta.prototype['minutes'] = undefined;

/**
 * @member {Number} seconds
 */
RelativeDelta.prototype['seconds'] = undefined;

/**
 * @member {Number} microseconds
 */
RelativeDelta.prototype['microseconds'] = undefined;

/**
 * @member {Number} year
 */
RelativeDelta.prototype['year'] = undefined;

/**
 * @member {Number} month
 */
RelativeDelta.prototype['month'] = undefined;

/**
 * @member {Number} day
 */
RelativeDelta.prototype['day'] = undefined;

/**
 * @member {Number} hour
 */
RelativeDelta.prototype['hour'] = undefined;

/**
 * @member {Number} minute
 */
RelativeDelta.prototype['minute'] = undefined;

/**
 * @member {Number} second
 */
RelativeDelta.prototype['second'] = undefined;

/**
 * @member {Number} microsecond
 */
RelativeDelta.prototype['microsecond'] = undefined;






export default RelativeDelta;

