# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# NOTE! THIS FILE IS AUTOMATICALLY GENERATED AND WILL BE OVERWRITTEN!
#
# IF YOU WANT TO MODIFY THIS FILE, YOU SHOULD MODIFY THE TEMPLATE
# `get_provider_info_TEMPLATE.py.jinja2` IN the `dev/breeze/src/airflow_breeze/templates` DIRECTORY


def get_provider_info():
    return {
        "package-name": "apache-airflow-providers-vespa",
        "name": "Vespa",
        "description": "`Vespa <https://vespa.ai/>`__\n",
        "integrations": [
            {
                "integration-name": "Vespa",
                "external-doc-url": "https://docs.vespa.ai",
                "how-to-guide": ["/docs/apache-airflow-providers-vespa/operators/vespa.rst"],
                "tags": ["software"],
            }
        ],
        "hooks": [{"integration-name": "Vespa", "python-modules": ["airflow.providers.vespa.hooks.vespa"]}],
        "operators": [
            {
                "integration-name": "Vespa",
                "python-modules": ["airflow.providers.vespa.operators.vespa_ingest"],
            }
        ],
        "triggers": [
            {
                "integration-name": "Vespa",
                "python-modules": ["airflow.providers.vespa.triggers.vespa_feed_trigger"],
            }
        ],
        "connection-types": [
            {
                "hook-class-name": "airflow.providers.vespa.hooks.vespa.VespaHook",
                "connection-type": "vespa",
                "conn-fields": {
                    "namespace": {
                        "label": "Namespace",
                        "schema": {"type": ["string", "null"], "default": "default"},
                        "description": 'Vespa document namespace. Groups documents within a document type for access control and distribution. Defaults to "default".\n',
                    },
                    "protocol": {
                        "label": "Protocol",
                        "schema": {"type": ["string", "null"], "default": "http"},
                        "description": 'Protocol used to connect to the Vespa endpoint, either "http" or "https". Ignored when the Endpoint field already includes a scheme (e.g. "https://…"). Defaults to "http".\n',
                    },
                    "vespa_cloud_secret_token": {
                        "label": "Vespa Cloud Secret Token",
                        "schema": {"type": ["string", "null"], "format": "password"},
                        "description": "Authentication token for Vespa Cloud. Used as an alternative to mTLS certificate authentication. Leave blank when using client certificates.\n",
                    },
                    "client_cert_path": {
                        "label": "Client Certificate Path",
                        "schema": {"type": ["string", "null"]},
                        "description": "Filesystem path to a PEM-encoded client certificate for mTLS authentication. Both this and Client Key Path must be set to enable mTLS; otherwise the hook falls back to token authentication.\n",
                    },
                    "client_key_path": {
                        "label": "Client Key Path",
                        "schema": {"type": ["string", "null"]},
                        "description": "Filesystem path to the PEM-encoded private key that corresponds to the client certificate. Required together with Client Certificate Path for mTLS authentication.\n",
                    },
                    "max_queue_size": {
                        "label": "Max Feed Queue Size",
                        "schema": {"type": ["integer", "null"]},
                        "description": "Maximum number of documents to buffer in the pyvespa async feed queue before blocking. Increase for higher throughput at the cost of memory. Uses the pyvespa default when unset.\n",
                    },
                    "max_workers": {
                        "label": "Max Feed Workers",
                        "schema": {"type": ["integer", "null"]},
                        "description": "Maximum number of concurrent worker threads used by the pyvespa async feed client. Uses the pyvespa default when unset.\n",
                    },
                    "max_connections": {
                        "label": "Max Feed Connections",
                        "schema": {"type": ["integer", "null"]},
                        "description": "Maximum number of HTTP connections the pyvespa feed client keeps open to the Vespa cluster. Uses the pyvespa default when unset.\n",
                    },
                },
                "ui-field-behaviour": {
                    "hidden-fields": ["login", "password", "extra"],
                    "relabeling": {"host": "Endpoint", "schema": "Document Type"},
                    "placeholders": {
                        "host": "vespa-endpoint.example.com",
                        "schema": "my_document_type",
                        "protocol": "https",
                        "namespace": "my_namespace",
                        "client_cert_path": "/path/to/client.pem",
                        "client_key_path": "/path/to/client.key",
                    },
                },
            }
        ],
    }
