/*!
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
import {
  FormControl,
  FormLabel,
  Input,
  VStack,
  ModalCloseButton,
  Button,
  ModalFooter,
  Box,
  Text,
  Spacer,
  HStack,
  Collapse,
} from "@chakra-ui/react";
import { autocompletion } from "@codemirror/autocomplete";
import { json } from "@codemirror/lang-json";
import { oneDark } from "@codemirror/theme-one-dark";
import CodeMirror, { lineNumbers } from "@uiw/react-codemirror";
import React, { useEffect, useCallback } from "react";
import { useForm, Controller } from "react-hook-form";

type DagParams = {
  configJson: string;
  dagId: string;
  logicalDate: string;
  runId?: string;
};

type TriggerDAGFormProps = {
  dagParams: DagParams;
  onClose: () => void;
  onTrigger: () => void;
  setDagParams: React.Dispatch<React.SetStateAction<DagParams>>;
};

const TriggerDAGForm: React.FC<TriggerDAGFormProps> = ({
  dagParams,
  onTrigger,
  setDagParams,
}) => {
  const [showDetails, setShowDetails] = React.useState(false);
  const { control, handleSubmit, setValue, watch } = useForm({
    defaultValues: {
      configJson: dagParams.configJson,
      logicalDate: dagParams.logicalDate,
      runId: dagParams.runId,
    },
  });

  useEffect(() => {
    // Update default values if dagParams change
    setValue("logicalDate", dagParams.logicalDate);
    setValue("runId", dagParams.runId);
    setValue("configJson", dagParams.configJson);
  }, [dagParams, setValue]);

  const handleChange = useCallback(
    (name: string, value: string) => {
      setDagParams((prev) => ({ ...prev, [name]: value }));
    },
    [setDagParams],
  );

  const handleReset = () => {
    setDagParams({
      configJson: "{}",
      dagId: dagParams.dagId,
      logicalDate: "",
      runId: "",
    });
    setValue("logicalDate", "");
    setValue("runId", "");
    setValue("configJson", "{}");
  };

  const handleJsonChange = (value: string) => {
    setValue("configJson", value);
    handleChange("configJson", value);
  };

  const isValidJson = () => {
    try {
      JSON.parse(watch("configJson"));

      return true;
    } catch {
      return false;
    }
  };

  const onSubmit = () => {
    onTrigger();
  };

  return (
    <>
      <ModalCloseButton />

      <VStack align="stretch" p={5} spacing={2}>
        <Button
          onClick={() => setShowDetails(!showDetails)}
          variant="outline"
          width="full"
        >
          {showDetails ? "Hide Advanced Options" : "Show Advanced Options"}
        </Button>

        <Collapse in={showDetails}>
          <VStack align="stretch" spacing={3}>
            <FormControl>
              <FormLabel size="sm">Logical date</FormLabel>
              <Controller
                control={control}
                name="logicalDate"
                render={({ field }) => (
                  <Input
                    {...field}
                    placeholder="yyyy-mm-ddThh:mm"
                    size="sm"
                    type="datetime-local"
                  />
                )}
              />
            </FormControl>

            <FormControl>
              <FormLabel size="sm">Run ID (Optional)</FormLabel>
              <Controller
                control={control}
                name="runId"
                render={({ field }) => (
                  <Input
                    {...field}
                    placeholder="Autogenerated if left empty"
                    size="sm"
                  />
                )}
              />
            </FormControl>

            <FormControl>
              <FormLabel size="sm">Configuration JSON</FormLabel>
              <Controller
                control={control}
                name="configJson"
                render={({ field }) => (
                  <CodeMirror
                    {...field}
                    extensions={[json(), autocompletion(), lineNumbers()]}
                    height="200px"
                    onChange={(value) => {
                      handleJsonChange(value);
                      field.onChange(value); // Update the field value
                    }}
                    style={{
                      border: "1px solid #CBD5E0",
                      borderRadius: "8px",
                      outline: "none",
                      padding: "2px",
                    }}
                    theme={oneDark}
                  />
                )}
              />
              {!isValidJson() && (
                <Box color="red.500" mt={2}>
                  <Text fontSize="sm">Invalid JSON format</Text>
                </Box>
              )}
            </FormControl>
          </VStack>
        </Collapse>
      </VStack>

      <ModalFooter>
        <HStack w="full">
          <Button colorScheme="red" onClick={handleReset}>
            Reset
          </Button>
          <Spacer />
          <Button
            colorScheme="green"
            isDisabled={!isValidJson()}
            onClick={() => {
              void handleSubmit(onSubmit)();
            }}
          >
            Trigger
          </Button>
        </HStack>
      </ModalFooter>
    </>
  );
};

export default TriggerDAGForm;
