%% Licensed to the Apache Software Foundation (ASF) under one
%% or more contributor license agreements.  See the NOTICE file
%% distributed with this work for additional information
%% regarding copyright ownership.  The ASF licenses this file
%% to you under the Apache License, Version 2.0 (the
%% "License"); you may not use this file except in compliance
%% with the License.  You may obtain a copy of the License at
%%
%%   http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing,
%% software distributed under the License is distributed on an
%% "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
%% KIND, either express or implied.  See the License for the
%% specific language governing permissions and limitations
%% under the License.

sequenceDiagram
    Scheduler->>+DagFileProcessorManager: Creates new process
    loop
        loop
            DagFileProcessorManager->>+DagFileProcessorManager: Refresh DAG directory
            DagFileProcessorManager->>+DagFileProcessor: Creates new process
            loop for each DAG
            DagFileProcessor-->>+DagFileProcessor: Load DAG File
            DagFileProcessor-->>+DagFileProcessor: Create DAG runs and Task Instances
            DagFileProcessor-->>+DagFileProcessor: Check SLAs
            end
            loop for each TI
            DagFileProcessor-->>+DagFileProcessor: Check TI dependency
            DagFileProcessor-->>+DagFileProcessor: Set state to SCHEDULED
            end
            DagFileProcessorManager-->>DagFileProcessorManager: Kill timed-out DAGFilePocessors
            DagFileProcessor-->>-DagFileProcessorManager: Return DAGs and import errors
        end
        DagFileProcessorManager-->>-Scheduler: Return DAGs and import errors
    end
    alt DAGs present in Scheduler
    Scheduler-->>+Scheduler: Enqueue TI to executor
    Scheduler-->>+Scheduler: Executor heartbeat
    end
