/*
 * Airflow API (Stable)
 * Apache Airflow management API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev@airflow.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ConnectionCollectionItem
 */
@JsonPropertyOrder({
  ConnectionCollectionItem.JSON_PROPERTY_CONNECTION_ID,
  ConnectionCollectionItem.JSON_PROPERTY_CONN_TYPE,
  ConnectionCollectionItem.JSON_PROPERTY_HOST,
  ConnectionCollectionItem.JSON_PROPERTY_LOGIN,
  ConnectionCollectionItem.JSON_PROPERTY_SCHEMA,
  ConnectionCollectionItem.JSON_PROPERTY_PORT
})

public class ConnectionCollectionItem {
  public static final String JSON_PROPERTY_CONNECTION_ID = "connection_id";
  private String connectionId;

  public static final String JSON_PROPERTY_CONN_TYPE = "conn_type";
  private String connType;

  public static final String JSON_PROPERTY_HOST = "host";
  private JsonNullable<String> host = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LOGIN = "login";
  private JsonNullable<String> login = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SCHEMA = "schema";
  private JsonNullable<String> schema = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PORT = "port";
  private JsonNullable<Integer> port = JsonNullable.<Integer>undefined();


  public ConnectionCollectionItem connectionId(String connectionId) {
    
    this.connectionId = connectionId;
    return this;
  }

   /**
   * Get connectionId
   * @return connectionId
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONNECTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getConnectionId() {
    return connectionId;
  }


  public void setConnectionId(String connectionId) {
    this.connectionId = connectionId;
  }


  public ConnectionCollectionItem connType(String connType) {
    
    this.connType = connType;
    return this;
  }

   /**
   * Get connType
   * @return connType
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_CONN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getConnType() {
    return connType;
  }


  public void setConnType(String connType) {
    this.connType = connType;
  }


  public ConnectionCollectionItem host(String host) {
    this.host = JsonNullable.<String>of(host);
    
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getHost() {
        return host.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_HOST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getHost_JsonNullable() {
    return host;
  }
  
  @JsonProperty(JSON_PROPERTY_HOST)
  public void setHost_JsonNullable(JsonNullable<String> host) {
    this.host = host;
  }

  public void setHost(String host) {
    this.host = JsonNullable.<String>of(host);
  }


  public ConnectionCollectionItem login(String login) {
    this.login = JsonNullable.<String>of(login);
    
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getLogin() {
        return login.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LOGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLogin_JsonNullable() {
    return login;
  }
  
  @JsonProperty(JSON_PROPERTY_LOGIN)
  public void setLogin_JsonNullable(JsonNullable<String> login) {
    this.login = login;
  }

  public void setLogin(String login) {
    this.login = JsonNullable.<String>of(login);
  }


  public ConnectionCollectionItem schema(String schema) {
    this.schema = JsonNullable.<String>of(schema);
    
    return this;
  }

   /**
   * Get schema
   * @return schema
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public String getSchema() {
        return schema.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCHEMA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSchema_JsonNullable() {
    return schema;
  }
  
  @JsonProperty(JSON_PROPERTY_SCHEMA)
  public void setSchema_JsonNullable(JsonNullable<String> schema) {
    this.schema = schema;
  }

  public void setSchema(String schema) {
    this.schema = JsonNullable.<String>of(schema);
  }


  public ConnectionCollectionItem port(Integer port) {
    this.port = JsonNullable.<Integer>of(port);
    
    return this;
  }

   /**
   * Get port
   * @return port
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public Integer getPort() {
        return port.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getPort_JsonNullable() {
    return port;
  }
  
  @JsonProperty(JSON_PROPERTY_PORT)
  public void setPort_JsonNullable(JsonNullable<Integer> port) {
    this.port = port;
  }

  public void setPort(Integer port) {
    this.port = JsonNullable.<Integer>of(port);
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectionCollectionItem connectionCollectionItem = (ConnectionCollectionItem) o;
    return Objects.equals(this.connectionId, connectionCollectionItem.connectionId) &&
        Objects.equals(this.connType, connectionCollectionItem.connType) &&
        Objects.equals(this.host, connectionCollectionItem.host) &&
        Objects.equals(this.login, connectionCollectionItem.login) &&
        Objects.equals(this.schema, connectionCollectionItem.schema) &&
        Objects.equals(this.port, connectionCollectionItem.port);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connectionId, connType, host, login, schema, port);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectionCollectionItem {\n");
    sb.append("    connectionId: ").append(toIndentedString(connectionId)).append("\n");
    sb.append("    connType: ").append(toIndentedString(connType)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

