{{/*
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements.  See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership.  The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied.  See the License for the
 specific language governing permissions and limitations
 under the License.
*/}}

################################
## Airflow StatsD ServiceMonitor
#################################
{{- if and .Values.statsd.enabled .Values.statsd.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "airflow.fullname" . }}-statsd
  namespace: {{ .Values.statsd.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- $labels := dict "tier" "airflow" "component" "statsd" "release" .Release.Name "chart" (printf "%s-%s" .Chart.Name .Chart.Version) "heritage" .Release.Service }}
    {{- if or .Values.labels .Values.statsd.labels }}
      {{- $labels = mustMerge (mustMerge .Values.statsd.labels .Values.labels) $labels }}
    {{- end }}
    {{- if .Values.statsd.serviceMonitor.additionalLabels }}
      {{- $labels = mustMerge .Values.statsd.serviceMonitor.additionalLabels $labels }}
    {{- end }}
    {{- toYaml $labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      tier: airflow
      component: statsd
      release: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: statsd-scrape
      path: /metrics
      interval: {{ .Values.statsd.serviceMonitor.interval }}
      {{- if .Values.statsd.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.statsd.serviceMonitor.scrapeTimeout }}
      {{- end }}
{{- end }}
